[settings]
auto_install = true
idiomatic_version_file_enable_tools = ["node"]
# python.uv_venv_auto = true


[tools]
ruby = "4.0"
node = "24.13.0"
golang = "latest"
jq = "latest"
ripgrep = "latest"
yq = "latest"
terraform = "latest"
"npm:claude" = "latest"

